{{- range $alg := .Values.algorithms }}
{{- $safeAlg := $alg | lower | replace "_" "-" | regexReplaceAll "[^a-z0-9-]+" "-" | trimAll "-" }}
{{- if not $safeAlg }}
{{- fail (printf "invalid algorithm name: %s" $alg) }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ta-service-{{ $safeAlg }}
  labels:
    app: ta-service-{{ $safeAlg }}
spec:
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: ta-service-{{ $safeAlg }}
  template:
    metadata:
      labels:
        app: ta-service-{{ $safeAlg }}
    spec:
      containers:
        - name: ta-service
          image: {{ $.Values.image }}
          command: ["python", "ta_service.py", "-ta_name", "{{ $alg }}"]
          env:
            - name: STOCKAPP_ENV
              value: {{ $.Values.env | quote }}
            - name: TA_SERVICE_IMAGE
              value: {{ $.Values.image | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
---
{{- end }}
