apiVersion: apps/v1
kind: Deployment
metadata:
  name: ta-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ta-service
  template:
    metadata:
      labels:
        app: ta-service
    spec:
      containers:
        - name: ta-service
          image: ta-service:latest
          env:
            - name: TA_NAME
              value: macd
            - name: TA_SERVICE_IMAGE
              value: ta-service:latest
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
